project:
  type: website
  output-dir: docs

website:
  title: "Predictive Maintenance & Reliability Engineering Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        menu:
          - text: "NASA RUL Prediction"
            href: projects/nasa-rul.qmd
          - text: "IoT Sensor Dashboard"
            href: projects/pdm-dashboard.qmd
          - text: "Cost & ROI Optimization"
            href: projects/maintenance-roi.qmd
          - text: "Methodology & Limitations"
            href: projects/methodology.qmd
          - text: "Olist BI Dashboard"
            href: projects/olist-dashboard.qmd
          - text: "Churn Prediction"
            href: projects/churn-prediction.qmd
          - text: "A/B Testing Analysis"
            href: projects/ab-testing.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  eval: true
